# Utility that updates labels based on keystone reusable workflow repository
name: "Monthly Label Timer"
on:
  # Manually run the job
  workflow_dispatch:
  # Periodically run the job
  # Every first day of the month at 1:27
  schedule:
    - cron: "1 27 1 * *"

jobs:
  # Runs reusable workflow (utility-update-labels.yml on the main branch) from keystone repository
  create-labels:
    name: "Update Labels"
    uses: escendit/keystone/.github/workflows/utility-update-labels.yml@main
